@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('Download_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('Build_Master')
        {
            steps
            {
                script
                {
                    cicd.buildArtifact()
                }
            }
        }
        stage('Deployment_Master')
        {
            parallel
            {
                
                stage('Deploy to QA1')
                {
                    steps
                    {
                        script
                        {
                            cicd.deployTomcat("DeclarativePipelinewithSharedLibraries","172.31.28.179","testapp")
                        }
                    }
                }
                stage('Deploy to QA2')
                {
                    steps
                    {
                        script
                        {
                             cicd.deployTomcat("DeclarativePipelinewithSharedLibraries","172.31.34.73","testapp")
                        }
                    }
                }
            }
           
        }
        stage('Testing_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("FunctionalTesting")
                    cicd.runSelenium("DeclarativePipelinewithSharedLibraries")
                }
            }
        }
        stage('Delivery_Master')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("DeclarativePipelinewithSharedLibraries","172.31.31.200","prodapp")
                }
            }
        }
    }
}
